-- AD_Column
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 3;
-- AD_Field
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 4;
-- AD_Menu
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 7;
-- AD_Message
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 9;
-- AD_RefList
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 11;
-- AD_RefTable
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 13;
-- AD_Reference
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 14;
-- AD_Tab
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 19;
-- AD_Table
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 21;
-- AD_ValRule
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 26;
-- AD_Window
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 27;
-- AD_Element
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 188;
-- AD_Process
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 199;
-- AD_ProcessPara
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 200;
-- AD_Form
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 313;
-- AD_FieldGroup
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 351;
-- AD_TreeNodeMM
UPDATE ADEMPIERE.AD_SEQUENCE SET CurrentNext = 2000000 WHERE AD_Sequence_ID = 502;
