ALTER TABLE LBR_TaxConfig_Region ADD COLUMN ValidFrom TIMESTAMP;
ALTER TABLE LBR_TaxConfig_ProductGroup ADD COLUMN ValidFrom TIMESTAMP;
ALTER TABLE LBR_TaxConfig_Product ADD COLUMN ValidFrom TIMESTAMP;
ALTER TABLE LBR_TaxConfig_BPGroup ADD COLUMN ValidFrom TIMESTAMP;
ALTER TABLE LBR_TaxConfig_BPartner ADD COLUMN ValidFrom TIMESTAMP;
ALTER TABLE LBR_ICMSMatrix ADD COLUMN ValidFrom TIMESTAMP;
ALTER TABLE LBR_ISSMatrix ADD COLUMN ValidFrom TIMESTAMP;